# USER=ijt PW=firenza
#   QSUB-r xetaxp
#   QSUB-A cray19
#   QSUB-lT 50
#   QSUB-lM 1500000w
#   QSUB
#chdir $TMPDIR

cat > data.$$ << EOF
(T,ALPHA) REACTION ON 136-XENON AT SUB-BARRIER ENERGIES
0.1000   25.0   0.50    0.2     5.00     0.9
  0. 10.   -.1   F F
0 66.0    146.   5.
0.00       1 0 0  24        0 .0
 1 0 0 0 4 0 0 0 0 0
TRITON   3.016  1.0        1  XE-136  135.9072 54.    -9.879
0.5   +1 0.0       0          0.0   +1 0.0
ALPHA    4.0026 2.0        1  I-135   134.910 53.0    0.000
0.0   +1 0.0       0          3.5    1 0.00

  1 0  0 135.90         1.25     0.65
  1 1  0 150.0  1.28    0.68    10.0    1.42    0.88
  2 0  0 134.91          1.25     0.65
  2 1  0 225.0  1.32    0.585   33.0    1.32    0.585
  3 0  0  3.0   0.0      1.25    0.65
  3 1  0  75.00 1.175   0.650
  3 3  0  8.00  1.175   0.650
  4 0  0 135.0  0.0      1.25    0.65
  4 1  0 60.000 1.250   0.650
  4 3  0  8.00  1.25    0.650
0
  1    1 2 1 0   1 0   0.5   0.5    3  0 19.8142  1  0  0  1  1.0000
  2    1 2 2 0   1 4   0.5   3.5    4  0  9.936   1  0  0  1  1.0000
 0
   2   1   7 0-1 0
       1   1   1   1  1.4142
      -2   1   1   2  1.000
   0   1   1
5.89
EOF
frescox < data.$$
\rm data.$$
\rm fort.*

#***********************************************************************
# 
#    Copyright 2018, I.J. Thompson
#
#    This file is part of FRESCOX.
#
#    FRESCOX is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    FRESCOX is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with FRESCOX. If not, see <http://www.gnu.org/licenses/>.
#
#    OUR NOTICE AND TERMS AND CONDITIONS OF THE GNU GENERAL PUBLIC
#    LICENSE
#
#    The precise terms and conditions for copying, distribution and
#    modification are contained in the file COPYING.
#
#***********************************************************************
