#chdir $TMPDIR
\rm fort.*
ln -s be7p-EM1.sf fort.35
ln -s be7p-EM1.lsf fort.75
#ln -s be7p-EM1.xsec fort.16
#ln -s be7p-EM1.xs2 fort.202
cat > data.$$ << EOF
7Be(p,g)8B  with Esbensen-Bertsch potental, E1 only
0.1      300.    0.3
 0.5 4.5  -1.0   F 0   0   0 00.
0  00.0  180.0    90. 
0.0        1 0 0   0   0   0 0 0.000 -1.0000 0.01
 1 0 0 0 1 0 0 0 0 0 0 0
proton  1.0078  1.0        1  7Be      7.0160 4.0      0.0
 0.5   1 0.0               1  1.5   -1 0.00
Gamma   0.0000  0.0        1  8B       8.0053 5.0     0.137
 1.0   1 0.0               3  2.0    1 0.00
0
  1 0  0 1.00   00.0    2.391   
  1 1  0 45.354 2.391   0.52    0.000
  1 3  0 4.898  2.391   0.52    0.000
  3 0  0 1.00   00.0    1.16    

  1    1 2-2 0   1 1   0.5   1.5   1   0   0.137  1  4  0
 0
   2   1   2-1 1 0 
      -2   1   1   1  1.00
   0   1   1 1 1
   0.005   200  4.005      
EOF
frescox < data.$$
\rm  data.$$                   
\rm fort*
exit
#***********************************************************************
# 
#    Copyright 2018, I.J. Thompson
#
#    This file is part of FRESCOX.
#
#    FRESCOX is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    FRESCOX is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with FRESCOX. If not, see <http://www.gnu.org/licenses/>.
#
#    OUR NOTICE AND TERMS AND CONDITIONS OF THE GNU GENERAL PUBLIC
#    LICENSE
#
#    The precise terms and conditions for copying, distribution and
#    modification are contained in the file COPYING.
#
#***********************************************************************
