#!/bin/tcsh 

get_version

if(! $?ARCH) setenv ARCH `uname -m`
if( -X hostsurname ) setenv MACH `hostsurname`
if(! $?MACH) then
     set try=$1
     if (-e fx${try}.def)  then
     if ($#argv != 0)  then
	 set MACH = $try
	 echo MACH=$MACH
	 shift
     endif
     endif
   endif
if(! $?MACH) set MACH = ${ARCH}

# change to any local preferences: 
#  copy & edit these lines yourself
if(${MACH} == sun4) set MACH=sun4-spl

if( ! -e ${MACH}) mkdir ${MACH}

echo chdir ${MACH}
chdir ${MACH}
ln -s ../*.f ../*.F ../*.inc ../*.h ../makefile ../*${MACH}* .  >& /dev/null
echo make ${argv}  MACH=${MACH}
make ${argv} MACH=${MACH}
